// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryCalculation.Models;

#nullable disable

namespace SalaryCalculation.Migrations
{
    [DbContext(typeof(SalaryCalculationContext))]
    [Migration("20250515121610_AddOrderToSalaryDetail")]
    partial class AddOrderToSalaryDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalaryCalculation.Models.SalaryCalculationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSalaryGross")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowEmployerCost")
                        .HasColumnType("bit");

                    b.Property<int>("StartMonth")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SalaryCalculations");
                });

            modelBuilder.Entity("SalaryCalculation.Models.SalaryDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CumulativeIncomeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumWageTaxDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SalaryCalculationId")
                        .HasColumnType("int");

                    b.Property<decimal>("SgkEmployeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SgkEmployerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StampTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEmployerCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnemploymentEmployeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnemploymentEmployerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SalaryCalculationId");

                    b.ToTable("SalaryDetails");
                });

            modelBuilder.Entity("SalaryCalculation.Models.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("IncomeTaxBracket1Limit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTaxBracket1Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTaxBracket2Limit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTaxBracket2Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTaxBracket3Limit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTaxBracket3Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTaxBracket4Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomeTaxBracket5Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumWageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SgkEmployeeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SgkEmployerRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StampTaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnemploymentEmployeeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnemploymentEmployerRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaxRates");
                });

            modelBuilder.Entity("SalaryCalculation.Models.SalaryDetail", b =>
                {
                    b.HasOne("SalaryCalculation.Models.SalaryCalculationRecord", "SalaryCalculation")
                        .WithMany("SalaryDetails")
                        .HasForeignKey("SalaryCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalaryCalculation");
                });

            modelBuilder.Entity("SalaryCalculation.Models.SalaryCalculationRecord", b =>
                {
                    b.Navigation("SalaryDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
